name: CI â€” Build, Push & Update GitOps Manifest

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: krishh13kk/k8s-go-app

jobs:
  build-and-push:
    name: Build Docker Image & Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest

  update-manifest:
    name: Update GitOps Manifest Repo
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout GitOps manifests repo
        uses: actions/checkout@v4
        with:
          repository: KK13krish/k8s-python-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops-repo

      - name: Update image tag in deployment.yaml
        run: |
          cd gitops-repo
          sed -i "s|image: krishh13kk/k8s-go-app:.*|image: krishh13kk/k8s-go-app:${{ github.sha }}|g" manifests/deployment.yaml
          cat manifests/deployment.yaml   # print for debug

      - name: Commit and push updated manifest
        run: |
          cd gitops-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add manifests/deployment.yaml
          git diff --cached --quiet || git commit -m "ci: update image to ${{ github.sha }}"
          git push
